export const envEmailJs = {
  NEXT_PUBLIC_EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID!,
  NEXT_PUBLIC_EMAILJS_NEWSLETTER_TEMPLATE:
    process.env.NEXT_PUBLIC_EMAILJS_NEWSLETTER_TEMPLATE!,
  NEXT_PUBLIC_EMAILJS_FORM_TEMPLATE: process.env.NEXT_PUBLIC_EMAILJS_FORM_TEMPLATE!,
  NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY!,
  NEXT_PUBLIC_APP_MAPBOX_TOKEN: process.env.NEXT_PUBLIC_APP_MAPBOX_TOKEN!,
};
