export const envEmailJs = {
  NEXT_PUBLIC_EMAILJS_SERVICE_ID: process.env.NEXT_PUBLIC_EMAILJS_SERVICE_ID!,
  NEXT_PUBLIC_EMAILJS_NEWSLETTER_TEMPLATE:
    process.env.NEXT_PUBLIC_EMAILJS_NEWSLETTER_TEMPLATE!,
  NEXT_PUBLIC_EMAILJS_PUBLIC_KEY: process.env.NEXT_PUBLIC_EMAILJS_PUBLIC_KEY!,
};
